#!/bin/env bash

check_2() {
  todo "2 - Services"
  todo "2.1     - inetd Services"
  todo "2.1.1   - Ensure chargen services are not enabled (Scored)"
  todo "2.1.2   - Ensure daytime services are not enabled (Scored)"
  todo "2.1.3   - Ensure discard services are not enabled (Scored)"
  todo "2.1.4   - Ensure echo services are not enabled (Scored)"
  todo "2.1.5   - Ensure time services are not enabled (Scored)"
  todo "2.1.6   - Ensure tftp server is not enabled (Scored)"
  todo "2.1.7   - Ensure xinetd is not enabled (Scored)"
  todo "2.2     - Special Purpose Services"
  todo "2.2.1.1 - Ensure time synchronization is in use (Not Scored)"
  todo "2.2.1.2 - Ensure ntp is configured (Scored)"
  todo "2.2.1.3 - Ensure chrony is configured (Scored)"
  todo "2.2.2   - Ensure X Window System is not installed (Scored)"
  todo "2.2.3   - Ensure Avahi Server is not enabled (Scored)"
  todo "2.2.4   - Ensure CUPS is not enabled (Scored)"
  todo "2.2.5   - Ensure DHCP Server is not enabled (Scored)"
  todo "2.2.6   - Ensure LDAP server is not enabled (Scored)"
  todo "2.2.7   - Ensure NFS and RPC are not enabled (Scored)"
  todo "2.2.8   - Ensure DNS Server is not enabled (Scored)"
  todo "2.2.9   - Ensure FTP Server is not enabled (Scored)"
  todo "2.2.10  - Ensure HTTP server is not enabled (Scored)"
  todo "2.2.11  - Ensure IMAP and POP3 server is not enabled (Scored)"
  todo "2.2.12  - Ensure Samba is not enabled (Scored)"
  todo "2.2.13  - Ensure HTTP Proxy Server is not enabled (Scored)"
  todo "2.2.14  - Ensure SNMP Server is not enabled (Scored)"
  todo "2.2.15  - Ensure mail transfer agent is configured for local-only mode (Scored)"
  todo "2.2.16  - Ensure NIS Server is not enabled (Scored)"
  todo "2.2.17  - Ensure rsh server is not enabled (Scored)"
  todo "2.2.18  - Ensure telnet server is not enabled (Scored)"
  todo "2.2.19  - Ensure tftp server is not enabled (Scored)"
  todo "2.2.20  - Ensure rsync service is not enabled (Scored)"
  todo "2.2.21  - Ensure talk server is not enabled (Scored)"
  todo "2.3     - Service Clients"
  todo "2.3.1   - Ensure NIS Client is not installed (Scored)"
  todo "2.3.2   - Ensure rsh client is not installed (Scored)"
  todo "2.3.3   - Ensure talk client is not installed (Scored)"
  todo "2.3.4   - Ensure telnet client is not installed (Scored)"
  todo "2.3.5   - Ensure LDAP client is not installed (Scored)"
}