#!/bin/env bash

check_3() {
  todo "3 - Network Configuration"
  todo "3.1   - Network Parameters (Host Only)"
  todo "3.1.1 - Ensure IP forwarding is disabled (Scored)"
  todo "3.1.2 - Ensure packet redirect sending is disabled (Scored)"
  todo "3.2   - Network Parameters (Host and Router)"
  todo "3.2.1 - Ensure source routed packets are not accepted (Scored)"
  todo "3.2.2 - Ensure ICMP redirects are not accepted (Scored)"
  todo "3.2.3 - Ensure secure ICMP redirects are not accepted (Scored)"
  todo "3.2.4 - Ensure suspicious packets are logged (Scored)"
  todo "3.2.5 - Ensure broadcast ICMP requests are ignored (Scored)"
  todo "3.2.6 - Ensure bogus ICMP responses are ignored (Scored)"
  todo "3.2.7 - Ensure Reverse Path Filtering is enabled (Scored)"
  todo "3.2.8 - Ensure TCP SYN Cookies is enabled (Scored)"
  todo "3.3   - IPv6"
  todo "3.3.1 - Ensure IPv6 router advertisements are not accepted (Scored)"
  todo "3.3.2 - Ensure IPv6 redirects are not accepted (Scored)"
  todo "3.3.3 - Ensure IPv6 is disabled (Not Scored)"
  todo "3.4   - TCP Wrappers"
  todo "3.4.1 - Ensure TCP Wrappers is installed (Scored)"
  todo "3.4.2 - Ensure /etc/hosts.allow is configured (Scored)"
  todo "3.4.3 - Ensure /etc/hosts.deny is configured (Scored)"
  todo "3.4.4 - Ensure permissions on /etc/hosts.allow are configured (Scored)"
  todo "3.4.5 - Ensure permissions on /etc/hosts.deny are 644 (Scored)"
  todo "3.5   - Uncommon Network Protocols"
  todo "3.5.1 - Ensure DCCP is disabled (Not Scored)"
  todo "3.5.2 - Ensure SCTP is disabled (Not Scored)"
  todo "3.5.3 - Ensure RDS is disabled (Not Scored)"
  todo "3.5.4 - Ensure TIPC is disabled (Not Scored)"
  todo "3.6   - Firewall Configuration"
  todo "3.6.1 - Ensure iptables is installed (Scored)"
  todo "3.6.2 - Ensure default deny firewall policy (Scored)"
  todo "3.6.3 - Ensure loopback traffic is configured (Scored)"
  todo "3.6.4 - Ensure outbound and established connections are configured (Not Scored)"
  todo "3.6.5 - Ensure firewall rules exist for all open ports (Scored)"
  todo "3.7   - Ensure wireless interfaces are disabled (Not Scored)"
}